### ISSUE TITLE
IceMelt SQL error

### ISSUE THREAD

**Issue by Morketh** [Morketh/icemelt#12]
```
Traceback (most recent call last):                                                                                                      ]   0% ETA:  --:--:--
  File "./IceMelt.py", line 152, in <module>
    cursor.execute(SQL,sqldata)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '), 'aegwynn')' at line 1")
```

so this needs to be fixed before IceMelt will work

**Comment by Morketh** [comment]
well IceMelt runs 1 guild into the database. and then we get this error

```
_mysql_exceptions.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`icemelt`.`guilds`, CONSTRAINT `FK_guilds_regions` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`))')
```

Well researching this i know exactly what the issue is im just not sure how to fix it.
essentially what is happening here is we are grabbing the Region ID from the regions table and then using that value we enter the guild with the RID unfortunately we are using a REPLACE INTO sql statement 

``` sql
REPLACE INTO `regions` (`name`) VALUES (%s);
```

The side effect of this is that the INDEX gets incremented and the resulting guild table fails to update. Ideally the INDEX shouldn't be updated as we are going to be adding the same Region Name multiple times.

**Comment by Morketh** [comment]
```
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'eu' for key 'name'")
```

well this is about the best i can do catch this error ignore it and move on in the program. we already know the region name is there and we dont care to add a duplicate entry so as far were concerned we can just forget about this error message
