### ISSUE TITLE
Configuration settings

### ISSUE THREAD

**Issue by Morketh** [Morketh/icemelt#17]
``` traceback
Traceback (most recent call last):
  File "./Cold-air-funnel.py", line 29, in <module>
    from ice import config
  File "/opt/icemelt/ice/config.py", line 38, in <module>
    _IN_MYSQL_HOST_ = ConfigSectionMap("IceMeltDB")['host']
  File "/opt/icemelt/ice/config.py", line 26, in ConfigSectionMap
    options = ice.options(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'IceMeltDB'
```

**Comment by Morketh** [comment]
the settings are in the configuration file (shown below) however i believe the error lies in not being able to locate the file in question

```
[IceMeltDB]
database: icemelt
user: icemelt
password: icemelt
host: localhost
port: 3306

[SqlLogs]
enabled: yes
path: /tmp/icemelt.sql
```

changing the file location has somewhat fixed this error but now we are having a problem with the 'path'

``` traceback
Traceback (most recent call last):
  File "./Cold-air-funnel.py", line 29, in <module>
    from ice import config
  File "/opt/icemelt/ice/config.py", line 46, in <module>
    _IN_SQL_FILE_ = ConfigSectionMap("IceMeltDB")['path']
KeyError: 'path'
```

**Comment by Morketh** [comment]
``` traceback
Traceback (most recent call last):
  File "./Cold-air-funnel.py", line 37, in <module>
    db = MySQLdb.connect(_IN_MYSQL_HOST_,_IN_MYSQL_USR_,_IN_MYSQL_PASS_,_IN_MYSQL_DB_)
NameError: name '_IN_MYSQL_HOST_' is not defined
```

well clearly if you look at the ice config those values are defined....
